name: Klouds.io Documentation
description: The Klouds.io Documentation
url: http://kloudsio.github.io/

title: Klouds.io Documentation
markdown: redcarpet
highlighter: pygments
gems:
    - jekyll-sitemap
